apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: dsachsmusic/order-a-greeting-inventory:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_PASSWORD
        - name: PLATFORM
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PLATFORM
        - name: PORT_FLASK_INVENTORY
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PORT_FLASK_INVENTORY
        
