#Environment variables defined here, similar to...
#them being defined in the ECS task definition when deploying to...
#AWS
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  #local machine IP, assuming Postgres is running...
  #locally on Windows laptop
  DB_HOST: "192.168.86.153"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "orders"
  PLATFORM: "minikube"
  FQDN_INVENTORY: "inventory.default.svc.cluster.local"
  PORT_INVENTORY: "81" #with minikube, use load balancer port, when testing locally, using port flask exposes
  PORT_FLASK_ORDERS: "5000" #with minikube, we'll simply run all Flask apps on port 5000
