apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: LoadBalancer
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 82 #using unique port for local testing of each service using minkube tunnel
      targetPort: 5000
