apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-access-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default  # The ServiceAccount name used by your pod
    namespace: default
roleRef:
  kind: Role
  name: api-access-role #enable the pods listed in (subjects) the access granted by our "deployment-access" role 
  apiGroup: rbac.authorization.k8s.io
