#to enable pods to access the kubernetes API and view...so our "orders" app can see how many 
#replicas there are, and scale up or down (logic is defined in the "orders" app code)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-access-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]